package com.kulakyokedici.kulakliksitesi.objects.exception;

public enum EErrorCode {
	
	INTERNAL_SERVER_ERROR,
	
	USER_NOT_FOUND,
	ADMIN_NOT_FOUND,
	SELLER_NOT_FOUND,
	SHOPPER_NOT_FOUND,
	ITEM_NOT_FOUND,
	CART_NOT_FOUND,
	
	USERTYPE_NOT_FOUND,
	CATEGORY_NOT_FOUND,
	
	VALIDATION_ERROR,
	
	AUTOEQ_HEADPHONE_NOT_FOUND,
	AUTOEQ_INVALID_ID,
	AUTOEQ_NOT_SUPPORTED_FOR_PRODUCT,
	AUTOEQ_SERVICE_UNAVAILABLE

}
