spring.application.name=kulakliksitesi

#server.servlet.context-path=/api/

# VERITABANI

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#test, performans ekstrasi saglamasi lazim
spring.jpa.open-in-view=false

# LOGGING

logging.level.org.springframework.security=DEBUG

# JWT

jwt-secret-key=${JWT_SECRET_KEY}

# HIBERNATE SEARCH (ELASTICSEARCH)

spring.jpa.properties.hibernate.search.backend.type=elasticsearch
spring.jpa.properties.hibernate.search.backend.uris=${ELASTISEARCH_URL:http://localhost:9200}

#geliştirme aşamasında her uygulama kalktığında indeks şemasını otomatik güncellesin
spring.jpa.properties.hibernate.search.backend.schema_management.strategy=drop-and-create

#mevcut veritabanındaki kayıtları uygulama başlarken Elasticsearch'e aktar (Mass Indexing için gerekli)
spring.jpa.properties.hibernate.search.automatic_indexing.synchronization.strategy=read-sync

#tek node olduğu için sniffer'i kapat
spring.jpa.properties.hibernate.search.backend.discovery.enabled=false

# otokonfigürasyonun ElasticsearchRestClientAutoConfiguration sınıfını devre dışı bırak
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration

# S3 (şu an sadece fotoğraflar için)

# Multipart Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# MinIO / S3
storage.endpoint=${MINIO_URL:http://localhost:9000}
storage.public-end-point=${MINIO_URL:http://localhost:9000}

storage.access-key=test
storage.secret-key=testtest

storage.bucket-product-images=headphoneapi-product-images

# AutoEQ
autoeq.service.url=${AUTOEQ_URL:http://localhost:8000}