spring.application.name=kulakliksitesi

#server.servlet.context-path=/api/

# VERITABANI

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#test, performans ekstrasi saglamasi lazim
spring.jpa.open-in-view=false

# LOGGING

logging.level.org.springframework.security=DEBUG

# JWT

jwt-secret-key=${JWT_SECRET_KEY}

# HIBERNATE SEARCH (ELASTICSEARCH)

spring.jpa.properties.hibernate.search.backend.type=elasticsearch
spring.jpa.properties.hibernate.search.backend.uris=http://localhost:9200

#geliştirme aşamasında her uygulama kalktığında indeks şemasını otomatik güncellesin
spring.jpa.properties.hibernate.search.backend.schema_management.strategy=drop-and-create

#mevcut veritabanındaki kayıtları uygulama başlarken Elasticsearch'e aktar (Mass Indexing için gerekli)
spring.jpa.properties.hibernate.search.automatic_indexing.synchronization.strategy=read-sync